### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jimaldon** [greydanus/greydanus.github.io#1]
I like your blog's theme, but I couldn't find any file or a mention of a license for your blog's source code. Could you perhaps mention it somewhere?

**Comment by greydanus** [comment]
Inspiration taken from https://karpathy.github.io/, as with most aspects of my research life.

**Comment by jimaldon** [comment]
You wouldn't mind me taking inspiration from your blog then?

**Comment by greydanus** [comment]
No problem, it would be an honor!
